apiVersion: v1
kind: Secret
metadata:
  namespace: apps-dev
  name: test-secrets
data:
  AWS_ACCESS_KEY_ID: NjA5NjI5MDY1MzA2 # Required.
  AWS_SECRET_ACCESS_KEY: YWRtaW4= # Required.
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: apps-dev
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID # Required.
      name: test-secrets # Required.
      key: AWS_ACCESS_KEY_ID # Required.
    - parameter: awsSecretAccessKey # Required.
      name: test-secrets # Required.
      key: AWS_SECRET_ACCESS_KEY # Required.
